[global]
    run as user = netdata
    memory mode = dbengine
    page cache size = 256
    dbengine disk space = 512
    update every = 1

[web]
    mode = static-threaded

[ml]
    enabled = yes

[health]
    enabled = yes

[plugins]
    python.d = yes
    go.d = yes
    charts.d = yes
    node.d = yes
