[stream]
    enabled = yes
    default port = 19999
    allow from = *
    enable compression = yes

[ffd8d7d4-81f9-4492-8165-c19d13032151]
    enabled = yes
    default history = 3600
    default memory mode = dbengine
